# This is the simple Travis configuration, which is intended for use
# on applications which do not require cross-platform and
# multiple-GHC-version support. For more information and other
# options, see:
#
# https://docs.haskellstack.org/en/stable/travis_ci/
#
# Copy these contents into the root directory of your Github project in a file
# named .travis.yml

# Use new container infrastructure to enable caching
sudo: false

# Do not choose a language; we provide our own build tools.
language: generic

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack
  - $HOME/.cabal

# Ensure necessary system libraries are present
addons:
  apt:
    packages:
      - libgmp-dev
      # this installs an older version of cabal which doesn't support new-build
      #- cabal-install

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
# Install a recent version of cabal which supports new-build
- stack install cabal-install

install:
# Build dependencies (stack)
- stack --no-terminal --install-ghc test --only-dependencies
# Build dependencies (cabal)
- cabal update
- ~/.local/bin/cabal new-build --only-dependencies

script:
# Build the package, its tests, and its docs and run the tests (stack)
- stack --no-terminal test --haddock --no-haddock-deps
# Build the package (cabal)
- ~/.local/bin/cabal new-build
