# This is the simple Travis configuration, which is intended for use
# on applications which do not require cross-platform and
# multiple-GHC-version support. For more information and other
# options, see:
#
# https://docs.haskellstack.org/en/stable/travis_ci/
#
# Copy these contents into the root directory of your Github project in a file
# named .travis.yml

# Use new container infrastructure to enable caching
sudo: false

# Do not choose a language; we provide our own build tools.
language: generic

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack
  - $HOME/.cabal
  - dist-newstyle
  - .stack-work

# Ensure necessary system libraries are present
#addons:
  #apt:
    #packages:
      # this installs the system version of ghc; we install ghc using stack instead
      #- libgmp-dev
      #- ghc
      # this installs an older version of cabal which doesn't support new-build
      #- cabal-install

env:
- BUILD=stack
- BUILD=cabal

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
# Install a recent version of cabal which supports new-build
- stack install cabal-install
# Make sure stack and cabal use the same ghc version
- export PATH="$(stack path --compiler-bin):$PATH"

install:
# Build dependencies (stack)
- if [ "$BUILD" == "stack" ]; then stack --no-terminal --install-ghc test --only-dependencies ;fi
# Build dependencies (cabal)
- if [ "$BUILD" == "cabal" ]; then ~/.local/bin/cabal update ;fi
- if [ "$BUILD" == "cabal" ]; then ~/.local/bin/cabal new-build --only-dependencies ;fi

script:
# Build the package, its tests, and its docs and run the tests (stack)
- if [ "$BUILD" == "stack" ]; then stack --no-terminal test --haddock --no-haddock-deps ;fi
# Build the package (cabal)
- if [ "$BUILD" == "cabal" ]; then ~/.local/bin/cabal new-build ;fi
